In [1]:
import numpy as np
#Exercise 4
#Task 1
matrix = np.ones((5, 5))
matrix[1, 1] = 0
matrix[1, 2] = 0
matrix[1, 3] = 0
matrix[2, 1] = 0
matrix[2, 2] = 0
matrix[2, 3] = 0
matrix[3, 1] = 0
matrix[3, 2] = 0
matrix[3, 3] = 0
print(matrix)

#Task 2
np.random.seed(42)
random_data = np.random.randn(100, 3)

col1 = random_data[:, 0]
col2 = random_data[:, 1]
col3 = random_data[:, 2]

col1_normalized = (col1 - col1.mean()) / col1.std()
col2_normalized = (col2 - col2.mean()) / col2.std()
col3_normalized = (col3 - col3.mean()) / col3.std()

normalized = np.column_stack([col1_normalized, col2_normalized, col3_normalized])

print("Column means:", normalized.mean(axis=0))
print("Column stds:", normalized.std(axis=0))

#Task 3
X = np.random.randn(50, 3)
true_theta = np.array([2.5, -1.2, 3.7])
y = X @ true_theta + np.random.randn(50) * 0.1

X_transpose = X.T
theta_hat = np.linalg.inv(X_transpose @ X) @ X_transpose @ y

print("Estimated theta:", theta_hat)
print("True theta:", true_theta)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[-2.60902411e-17  1.55431223e-17 -8.88178420e-18]
[1. 1. 1.]
Estimated theta: [ 2.51723721 -1.19783796  3.72399266]
True theta:  [ 2.5 -1.2  3.7]
Difference:  [0.01723721 0.00216204 0.02399266]


In [2]:
import pandas as pd
import numpy as np
#Exercise 5
np.random.seed(42)
n_students = 200
data = {
    'student_id': range(1000, 1000 + n_students),
    'major': np.random.choice(['CS', 'Math', 'Physics', 'Biology'], n_students),
    'year': np.random.choice([1, 2, 3, 4], n_students),
    'exam_score': np.random.normal(75, 10, n_students).clip(0, 100),
    'assignments_completed': np.random.randint(0, 11, n_students),
    'hours_studied': np.random.normal(15, 5, n_students).clip(1, 40)
}
df = pd.DataFrame(data)

df.loc[np.random.choice(n_students, 10), 'exam_score'] = np.nan
df.loc[np.random.choice(n_students, 5), 'hours_studied'] = np.nan

#Task 1
print(df.shape)
print(df.dtypes)
print(df.isnull().sum())

#Fill missing exam_score with mean of same major
for major in df['major'].unique():
    mask = (df['major'] == major) & (df['exam_score'].isnull())
    mean_score = df[df['major'] == major]['exam_score'].mean()
    df.loc[mask, 'exam_score'] = mean_score

#Fill missing hours_studied with median of same year
for year in df['year'].unique():
    mask = (df['year'] == year) & (df['hours_studied'].isnull())
    median_hours = df[df['year'] == year]['hours_studied'].median()
    df.loc[mask, 'hours_studied'] = median_hours

print("Missing values after fill:", df.isnull().sum())

#Task 2
avg_by_major = df.groupby('major')['exam_score'].mean()
print("Average score by major:")
print(avg_by_major)

best_major = avg_by_major.idxmax()
print("Best major:", best_major)

correlation = df['hours_studied'].corr(df['exam_score'])
print("Correlation:", correlation)

def get_performance(score):
    if score > 90:
        return 'Excellent'
    elif score >= 80:
        return 'Good'
    elif score >= 70:
        return 'Average'
    else:
        return 'Needs Improvement'

df['performance'] = df['exam_score'].apply(get_performance)
print(df['performance'].value_counts())

#Task 3
group_stats = df.groupby(['major', 'year']).agg(
    num_students=('student_id', 'count'),
    avg_exam_score=('exam_score', 'mean'),
    avg_hours_studied=('hours_studied', 'mean')
)
print(group_stats)

top5 = df.nlargest(5, 'exam_score')[['student_id', 'major', 'year', 'exam_score']]
print("Top 5 students:")
print(top5)

pivot = df.pivot_table(values='exam_score', index='major', columns='year', aggfunc='mean')
print("Pivot table:")
print(pivot)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   student_id             200 non-null    int64  
 1   major                  200 non-null    object 
 2   year                   200 non-null    int64  
 3   exam_score             190 non-null    float64
 4   assignments_completed  200 non-null    int64  
 5   hours_studied          195 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 9.5+ KB
None
student_id                0
major                     0
year                      0
exam_score               10
assignments_completed     0
hours_studied             5
dtype: int64

Missing values after fill: 0
Avg score by major:major
Biology    75.50
CS         76.43
Math       74.68
Physics    75.41
Name: exam_score, dtype: float64

Major with highest average: CS (76.43)

Correlation (hours_studied vs exam_

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
#Exercise 6
# Task 1
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

axes[0].hist(df['exam_score'], bins=20)
axes[0].set_title("Exam Score Distribution")
axes[0].set_xlabel("Exam Score")
axes[0].set_ylabel("Count")

majors = df['major'].unique()
data_to_plot = [df[df['major'] == m]['exam_score'].values for m in majors]
axes[1].boxplot(data_to_plot, labels=majors)
axes[1].set_title("Exam Scores by Major")
axes[1].set_xlabel("Major")
axes[1].set_ylabel("Exam Score")

plt.tight_layout()
plt.show()

# Task 2
plt.figure(figsize=(8, 6))

for major in df['major'].unique():
    subset = df[df['major'] == major]
    plt.scatter(subset['hours_studied'], subset['exam_score'], label=major, alpha=0.6)

m, b = np.polyfit(df['hours_studied'], df['exam_score'], 1)
x = df['hours_studied'].sort_values()
plt.plot(x, m * x + b, color='black', linestyle='--', label='Regression line')

plt.title("Hours Studied vs Exam Score")
plt.xlabel("Hours Studied")
plt.ylabel("Exam Score")
plt.legend()
plt.show()

# Task 3
fig, axes = plt.subplots(2, 2, figsize=(12, 10))

avg_scores = df.groupby('major')['exam_score'].mean()
axes[0, 0].bar(avg_scores.index, avg_scores.values)
axes[0, 0].set_title("Average Exam Score by Major")
axes[0, 0].set_xlabel("Major")
axes[0, 0].set_ylabel("Score")

year_counts = df['year'].value_counts().sort_index()
axes[0, 1].bar(year_counts.index, year_counts.values)
axes[0, 1].set_title("Number of Students by Year")
axes[0, 1].set_xlabel("Year")
axes[0, 1].set_ylabel("Count")

corr = df[['exam_score', 'assignments_completed', 'hours_studied']].corr()
sns.heatmap(corr, annot=True, fmt=".2f", ax=axes[1, 0])
axes[1, 0].set_title("Correlation Matrix")

order = ['Excellent', 'Good', 'Average', 'Needs Improvement']
data_violin = [df[df['performance'] == p]['exam_score'].values for p in order]
axes[1, 1].violinplot(data_violin)
axes[1, 1].set_xticks([1, 2, 3, 4])
axes[1, 1].set_xticklabels(order)
axes[1, 1].set_title("Exam Score by Performance")
axes[1, 1].set_ylabel("Exam Score")

plt.tight_layout()
plt.show()

In [ ]:
#Exercise 7

np.random.seed(42)
n_customers = 500

ages = np.random.randint(18, 70, n_customers)
income = np.random.normal(50000, 20000, n_customers).clip(15000, 150000)
purchase_freq = np.random.poisson(5, n_customers)
avg_purchase_value = np.random.normal(100, 30, n_customers).clip(10, 500)

customers = pd.DataFrame({
    'age': ages,
    'income': income,
    'purchase_frequency': purchase_freq,
    'avg_purchase_value': avg_purchase_value
})

#CLV
max_frequency = customers['purchase_frequency'].max()
customers['churn_risk'] = 1 - (customers['purchase_frequency'] / max_frequency)
customers['clv'] = customers['purchase_frequency'] * customers['avg_purchase_value'] * (1 + customers['churn_risk'])

#Age groups
customers['age_group'] = 'unknown'
for i in customers.index:
    age = customers.loc[i, 'age']
    if age <= 25:
        customers.loc[i, 'age_group'] = '18-25'
    elif age <= 35:
        customers.loc[i, 'age_group'] = '26-35'
    elif age <= 50:
        customers.loc[i, 'age_group'] = '36-50'
    else:
        customers.loc[i, 'age_group'] = '51-70'

#Stats by age group
group_stats = customers.groupby('age_group').agg(
    num_customers=('clv', 'count'),
    avg_income=('income', 'mean'),
    avg_clv=('clv', 'mean'),
    total_clv=('clv', 'sum')
)
print(group_stats)

#Top 10% customers
threshold = customers['clv'].quantile(0.90)
top_customers = customers[customers['clv'] >= threshold]
print("Top 10% customers:")
print(top_customers.head(10))

#Visualizations
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

for group in customers['age_group'].unique():
    subset = customers[customers['age_group'] == group]
    axes[0].scatter(subset['income'], subset['clv'], label=group, alpha=0.5)
axes[0].set_title("Income vs CLV")
axes[0].set_xlabel("Income")
axes[0].set_ylabel("CLV")
axes[0].legend()

avg_clv = customers.groupby('age_group')['clv'].mean()
axes[1].bar(avg_clv.index, avg_clv.values)
axes[1].set_title("Average CLV by Age Group")
axes[1].set_xlabel("Age Group")
axes[1].set_ylabel("Average CLV")

corr = customers[['age', 'income', 'purchase_frequency', 'avg_purchase_value', 'clv']].corr()
sns.heatmap(corr, annot=True, fmt=".2f", ax=axes[2])
axes[2].set_title("Correlation Matrix")

plt.tight_layout()
plt.show()